"use client";
import Head from "next/head";
import { AnimatePresence } from "framer-motion";
import Preloader from "../components/Preloader";
import Footer from "@/components/Footer";
import React, { useState, useEffect } from "react";
import Hero2 from "@/components/Hero";
import Header from "@/components/Header";
import Header2 from "@/components/header2";
import Wedo from "@/components/Wedo";
import What2 from "../components/What2";
import Link from "../components/Link";
import Test from "@/components/Test";
import Platform from "@/components/Platform";
import YouTube2 from "@/components/Youtube2";


export default function Home() {
  const [isLoading, setIsLoading] = useState(true);
  const [isHeroVisible, setIsHeroVisible] = useState(false);

  useEffect(() => {
    const delayHero = async () => {
      // Simulate some loading time
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Set isLoading to false to hide the preloader
      setIsLoading(false);

      // Set isHeroVisible to true to allow the Hero component to mount
      setIsHeroVisible(true);
    };

    delayHero();
  }, []);

  return (
    <div>
      <Head>
        <title>Leadafrique International</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AnimatePresence>{isLoading && <Preloader />}</AnimatePresence>

      {isHeroVisible && <Hero2 />}

      <div className="bg8">
        <What2 />
        <Wedo />
      </div>
      <Test />
      <Link />
      <Platform />
      <YouTube2 />

      <Footer />
    </div>
  );
}
